# Generated by Django 5.2.4 on 2025-12-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only when discount_type = percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', max_length=20),
        ),
    ]
