# Generated by Django 5.2.4 on 2025-12-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralReward',
        ),
    ]
