# Generated by Django 5.2.4 on 2025-11-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_variant_alter_cartitem_quantity'),
        ('products', '0004_alter_product_varients_colour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
