# Generated by Django 5.2.4 on 2025-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='return_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
