# Generated by Django 5.2.4 on 2025-11-12 07:42

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantimage',
            options={'ordering': ['-is_primary', 'created_at']},
        ),
        migrations.AddField(
            model_name='variantimage',
            name='created_at',
            field=models.DateTimeField(default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantimage',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
