# Generated by Django 5.2.4 on 2025-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_images',
            options={'ordering': ['-is_primary', 'created_at']},
        ),
        migrations.AddField(
            model_name='product_images',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
