# Generated by Django 5.2.4 on 2025-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variantimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_varients',
            name='colour',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('White', 'White'), ('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=20),
        ),
    ]
